#file cấu hình ứng dụng
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mySQL://localhost:3306/instagram
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      user_sql_comments: true

# Lí do tại sao lại dùng yml ?? chờ docx nha ae
